#@ load("@ytt:data", "data")  # for reading data values (generated via ytt's data-values-schema-inspect mode).
#@ load("@ytt:yaml", "yaml")  # for dynamically decoding the output of ytt's data-values-schema-inspect
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: #@ data.values.profile + "-pkg-repo"
spec:
  fetch:
    imgpkgBundle:
      image: #@ data.values.registry + "/" + data.values.profile + "-pkg-repo:" + data.values.packageRepoVersion