---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  annotations:
    kbld.k14s.io/images: |
      - origins:
        - resolved:
            tag: 0.0.1
            url: localhost:5001/gitopscon/lg-pkg-repo:0.0.1
        url: localhost:5001/gitopscon/lg-pkg-repo@sha256:6cf68badbc72906dc0e72fda22729c39f0986b4f21574d5b993ed0bce5c85997
  name: lg-pkg-repo
spec:
  fetch:
    imgpkgBundle:
      image: localhost:5001/gitopscon/lg-pkg-repo@sha256:6cf68badbc72906dc0e72fda22729c39f0986b4f21574d5b993ed0bce5c85997
