apiVersion: kbld.k14s.io/v1alpha1
kind: Config
#! build image
sources:
- image: localhost:5001/gitopscon/hello-app
  path: temp/src/hello-app
  pack:
    build:
      builder: paketobuildpacks/builder
#! publish (push) image
destinations:
- image: localhost:5001/gitopscon/hello-app
  newImage: localhost:5001/gitopscon/hello-app:latest
