apiVersion: kbld.k14s.io/v1alpha1
kind: Config
#! build image
sources:
- image: gcr.io/pa-mbrodi/gitopscon/hello-app
  path: temp/src/hello-app
  pack:
    build:
      builder: paketobuildpacks/builder
#! publish (push) image
destinations:
- image: gcr.io/pa-mbrodi/gitopscon/hello-app
  newImage: gcr.io/pa-mbrodi/gitopscon/hello-app
  tags: [latest]

