apiVersion: kbld.k14s.io/v1alpha1
kind: Config
#! build image
sources:
- image: localhost:5001/giant-app
  path: temp/src/giant-app
  pack:
    build:
      builder: paketobuildpacks/builder
#! publish (push) image
destinations:
- image: localhost:5001/giant-app
  newImage: localhost:5001/giant-app
