---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  annotations:
    kbld.k14s.io/images: |
      - origins:
        - resolved:
            tag: 0.0.1
            url: gcr.io/fe-ciberkleid/gitopscon/lg-pkg-repo:0.0.1
        url: gcr.io/fe-ciberkleid/gitopscon/lg-pkg-repo@sha256:ab24002163c8888df15294443043efbd1b3eff58af4284f5d3b60f1af5054012
  name: lg-pkg-repo
spec:
  fetch:
    imgpkgBundle:
      image: gcr.io/fe-ciberkleid/gitopscon/lg-pkg-repo@sha256:ab24002163c8888df15294443043efbd1b3eff58af4284f5d3b60f1af5054012
