apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: sm-vic-hello-app
spec:
  serviceAccountName: default-ns-sa
  packageRef:
    refName: sm-hello-app.corp.com
    versionSelection:
      constraints: 0.5.4
  values:
    - secretRef:
        name: sm-vic-hello-app-values
---
apiVersion: v1
kind: Secret
metadata:
  name: sm-vic-hello-app-values
stringData:
  values.yml: |
    helloApp:
      name: sm-vic-hello-app
      message: "Beautiful Victoria"
