#@data/values-schema
#! This file contains default config values
#! To override these values, use override files
---
namespace:
  name: hello-app
  #@schema/desc "Set to null to omit Namespace resource"
  #@schema/type any=True
  owner: null

helloApp:
  name: hello-app
  #@schema/desc "Name used in hello message from app when app is pinged."
  message: "default configuration"

  memRequest: "128Mi"
  cpuRequest: "500m"
  memLimit: "256Mi"
  cpuLimit: "1000m"

  ingress:
    hostname: null
    domain: null
    class: null
    secret:
      certificate: null
      privateKey: null
