export KCTRL_DEMO_TEMP=$PWD/temp/kctrl
export KCTRL_PKG_NAME=certman
export KCTRL_PKG_VERSION=1.9.0
export KCTRL_PKG_DIR=$KCTRL_DEMO_TEMP/package-contents/$KCTRL_PKG_NAME-package
export KCTRL_REPO_DIR=$KCTRL_DEMO_TEMP/lg
export KCTRL_PKG_REPO_VERSION=0.0.1