#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: #@ data.values.packageName + "." + data.values.version
spec:
  refName: #@ data.values.packageName
  version: #@ data.values.version
  releaseNotes: |
    Initial release of the app package
  valuesSchema:
    openAPIv3: #@ yaml.decode(data.values.openapi)["components"]["schemas"]["dataValues"]
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: #@ data.values.registry + "/" + data.values.bundleName + ":" + data.values.version
      template:
        - ytt:
            paths:
              - "config/"
              - "overlay/"
              - "values/"
        - kbld:
            paths:
              - ".imgpkg/images.yml"
              - "-"
      deploy:
        - kapp: {}
