#@ load("@ytt:data", "data")  # for reading data values (generated via ytt's data-values-schema-inspect mode).
#@ load("@ytt:yaml", "yaml")  # for dynamically decoding the output of ytt's data-values-schema-inspect
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: #@ "lg-hello-app.corp.com." + data.values.version
spec:
  refName: lg-hello-app.corp.com
  version: #@ data.values.version
  releaseNotes: |
    Initial release of the simple app package
  valuesSchema:
    openAPIv3: #@ yaml.decode(data.values.openapi)["components"]["schemas"]["dataValues"]
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: #@ "gcr.io/pa-mbrodi/gitopscon/lg-hello-app-bundle:" + data.values.version
      template:
        - ytt:
            paths:
              - "config/"
              - "overlay/"
              - "values/"
        - kbld:
            paths:
              - ".imgpkg/images.yml"
              - "-"
      deploy:
        - kapp: {}
