#@ load("@ytt:data", "data")
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: #@ data.values.packageName
spec:
  displayName: #@ data.values.appName + " App"
  longDescription: #@ data.values.appName + " app for demoing"
  shortDescription: #@ data.values.appName + " app for deployment to Kubernetes"
  categories:
    - demo
