#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-ns-sa
  namespace: #@ data.values.namespace.name
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ns-role
  namespace: #@ data.values.namespace.name
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ns-role-binding
  namespace: #@ data.values.namespace.name
subjects:
  - kind: ServiceAccount
    name: default-ns-sa
    namespace: #@ data.values.namespace.name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-ns-role