#@data/values-schema
#! This file contains default config values
#! To override these values, use override files
---
namespace:
  name: giant-app
  #! Set to null to omit Namespace resource
  owner: null

giantApp:
  name: giant-app
  message: "default configuration"

  memRequest: "128Mi"
  cpuRequest: "500m"
  memLimit: "256Mi"
  cpuLimit: "1000m"

  ingress:
    hostname: null
    domain: null
    class: null
    secret:
      certificate: null
      privateKey: null
