apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: lg-giant-app
spec:
  serviceAccountName: default-ns-sa
  packageRef:
    refName: lg-giant-app.corp.com
    versionSelection:
      constraints: 1.0.0