#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: #@ data.values.profile + "-pkg-repo"
spec:
  fetch:
    imgpkgBundle:
      image: #@ data.values.registry + "/" + data.values.profile + "-pkg-repo:" + data.values.packageRepoVersion